---
layout: post
title: Rails fields_forのN+1問題・エラー表示
date: 2016-07-05 02:49:52
categories: ruby-on-rails
---
<!-- {% raw %} -->
<p>現状以下の問題を認識しています。</p>

<h3>登場モデル</h3>

<p>以下の様なモデル例で説明します。</p>

<p>Account has_many posts<br>
Post belongs_to category<br>
Category</p>

<ul>
<li><code>accepts_nested_attributes_for :posts</code>でAccountのedit時にpostを複数編集</li>
</ul>

<h3><code>&lt;%= f.fields_for :posts do |f| %&gt;</code>の場合</h3>

<p>上記のfileds_for内に、<code>f.object.category.try(:name)</code>などのように記述するとN+1問題が発生します。</p>

<h3><code>&lt;%= f.fields_for :posts, f.object.posts.includes(:category) do |f| %&gt;</code>の場合</h3>

<p>N+1問題は解決しますが、Postモデルに<code>validates :title, presence: true</code>としていた場合に、<code>f.object.posts.includes(:category)</code>を指定しているとpostsが再読み込みされてしまいエラー情報が消えてしまう。</p>

<hr>

<p>上記のN+1問題を解決しつつ、postsモデルのerrors情報を保持するにはどのように記述すればよいのでしょうか？</p>

<p>コード例は以下のリンクにあります。</p>

<p><a href="https://github.com/kntmrkm-public/fields-for-example" rel="nofollow">https://github.com/kntmrkm-public/fields-for-example</a></p>
<!-- {% endraw %} -->
