---
layout: post
title: クラスを使った例外処理
date: 2017-05-06 22:17:07
categories: c++
---
<p>このような関数を書いた場合、どのようにmain関数でtry、catchすればいいのでしょうか？よろしくお願いします。言語はｃ＋＋です。クラスを補足しました。説明不足ですみません。　　</p>

```
template &lt;class T&gt;class DynArray {
    T* pData;
    int size;　public:
    DynArray() {
        pData = NULL;
        size = 0;
    }

    DynArray(const DynArray&amp; theOther) {
        size = 0;
        pData = NULL;
        this = theOther;
    }

    ~DynArray() {
        if (pData != NULL)
            delete[] pData;
    }

    void InsertAt(const T&amp; newElement, int position);
    void RemoveAt(int position);
};

template&lt;class T&gt;void DynArray&lt;T&gt;::RemoveAt(int position) {
    if (position &gt; size)
        throw new length_error("Position out of the size of DynArray");

    if (size == 1) {
        delete[] pData;
        size = 0;
        return;
    }
    size--;

    T* pTemp = new T[size];

    {
        int i, j;
        for (i = 0, j = 0; i &lt; size; i++, j++) {
            if (j == position) {
                j--; continue;
            }
            pTemp[i] = pData[j];
        }
    }

    delete[] pData;
    pData = pTemp;

}
```
