---
layout: post
title: RuntimeError: Dimension out of range (expected to be in range of [-1, 0], but got 1)と出力されます。
date: 2018-09-18 09:06:34
categories: python python3 pytorch
---
<blockquote>
  <p><a href="https://github.com/pytry3g/pytorch-example/tree/master/nlp/rnn/wikipedia" rel="nofollow noreferrer">https://github.com/pytry3g/pytorch-example/tree/master/nlp/rnn/wikipedia</a></p>
</blockquote>

<p>上記githubのtest_model.pyとtrain.pyを実行すると、共に、<br>
以下のエラーが出てしまいます。</p>

<pre><code>Traceback (most recent call last):
File "/home/yudai/デスクトップ/wikipedia/test_model.py", line 53, in &lt;module&gt;
model = RNN(n_vocab, embedding_dim, hidden_dim)
File "/home/yudai/デスクトップ/wikipedia/test_model.py", line 22, in init
self.decoder = nn.Linear(hidden_dim, n_vocab)
File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/linear.py", line 46, in init
self.reset_parameters()
File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/linear.py", line 49, in reset_parameters
stdv = 1. / math.sqrt(self.weight.size(1))
RuntimeError: Dimension out of range (expected to be in range of [-1, 0], but got 1)
</code></pre>

<p>本当に困っています。<br>
何卒、よろしくお願い致します。</p>

<h1>環境</h1>

<p>OS は Ubuntu です。</p>

<pre><code>$ uname -a
Linux NAGARE 4.15.0-30-generic #32-Ubuntu SMP Thu Jul 26 17:42:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
</code></pre>

<p>ライブラリ:pytorch</p>

<pre><code>torch                             0.4.1    
torchvision                       0.2.1

$ python3 -V
Python3.6.6+
</code></pre>
