---
layout: post
title: pyton3.6で input()がエラーになります。
date: 2018-09-06 08:38:08
categories: python python3
---
<!-- {% raw %} -->
<p>初心者です。<br>
Python3.6.2で以下のinput()がエラーになります。</p>

<p>原因と修正方法をお教えください。</p>

<p>OS:windows10<br>
Version:python3.6.5<br>
(Anaconda3-5.2.0-Windows-x86_64.exeでインストールしました。)</p>

<pre><code>E:\work\python\lesson&gt;python
Python 3.6.5 |Anaconda, Inc.| (default, Mar 29 2018, 13:32:41) [MSC v.1900 64 bit (AMD64)] on win32
</code></pre>

<p>test_inpStr.pyをコマンドプロンプトから実行すると</p>

<pre><code>#! python3                    
# -*-coding:utf-8-*-          
print("文字を入力してみよう。") 
x=input()                     
print(x,"が入力されたよ。")
</code></pre>

<p>以下のエラーとなります。何故でしょうか???</p>

<pre><code>E:\work\python\lesson&gt;test_inpStr.py
文字を入力してみよう。
aaa
Traceback (most recent call last):
  File "E:\work\python\lesson\test_inpStr.py", line 5, in ?
    x=input()
  File "&lt;string&gt;", line 0, in ?
NameError: name 'aaa' is not defined
</code></pre>
<!-- {% endraw %} -->
