---
layout: post
title: DjangoでLet's Encryptの証明書発行ができません＞＜。
date: 2018-07-19 04:44:20
categories: django ssl letsencrypt
---
<!-- {% raw %} -->
<p>お忙しいところ申し訳ないのですが、DjangoでSSL化を考えていたのですが、Let's Encryptの証明書の発行ができません。</p>

<p>＜開発環境＞<br>
Conoha VPS 1G<br>
OS CentOS7.5<br>
Apache 2.4.6<br>
python 3.6.5<br>
Django 2.0.7</p>

<p><a href="https://hombre-nuevo.com/vps/vps0023/" rel="nofollow noreferrer">https://hombre-nuevo.com/vps/vps0023/</a><br>
を参考に設定しましたが、証明書の発行でエラーが出ます。</p>

<p>＜Django 側の設定＞</p>

<p>・settings.py に追記</p>

<pre class="lang-py prettyprint-override"><code>CERT_ROOT = os.path.join(BASE_DIR, '.well-known')
CERT_URL = '/.well-known/'

ALLOWED_HOSTS = ['www.[取得したドメイン]','[取得したドメイン]']
</code></pre>

<p>・urls.py　に追記</p>

<pre class="lang-py prettyprint-override"><code>from django.conf.urls.static import static
from django.conf import settings

urlpatterns += static(settings.CERT_URL, document_root=settings.CERT_ROOT)
</code></pre>

<p>・テスト用の静的ファイルを作成</p>

<pre><code>/var/www/cgi-bin/***/---/.well-known/acme-challenge/test.html
</code></pre>

<p>(WEBブラウザにて表示されています)<br>
***　→　Django Project name<br>
--- →　Django app name</p>

<p>＜ポート＞<br>
80<br>
443<br>
開放済み</p>

<p>＜証明書発行時コマンド＞</p>

<pre><code>certbot certonly --webroot -w /var/www/cgi-bin/***/---/.well-known/ -d [取得したドメイン wwwなし] --email=[メールアドレス]
</code></pre>

<p>＜エラー内容＞</p>

<pre><code>IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: [取得したドメイン wwwなし]
   Type:   unauthorized
   Detail: Invalid response from
   http://[取得したドメイン wwwなし]/.well-known/acme-challenge/oMwTbqaN_LocYGh1OywMgoES6LZkaeY5TJIfwkIu8Jc:
   "&lt;!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"&gt;
   &lt;html&gt;&lt;head&gt;
   &lt;title&gt;404 Not Found&lt;/title&gt;
   &lt;/head&gt;&lt;body&gt;
   &lt;h1&gt;Not Found&lt;/h1&gt;
   &lt;p"

   To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A/AAAA record(s) for that domain
   contain(s) the right IP address.
</code></pre>

<p>ドメインは、ムームードメインにて取得し、現状SSLなしで正常に動いています。<br>
DNSの設定ですが、</p>

<p>＜DNSの設定＞</p>

<pre><code>A(通常)    @ TTL 3600 [IP-Adress]
A(通常)    www TTL 3600 [IP-Adress]
NS @ TTL 3600 ns-a1.conoha.io
NS @ TTL 3600 ns-a2.conoha.io
NS @ TTL 3600 ns-a3.conoha.io
</code></pre>

<p>＜Apache .conf＞</p>

<pre><code>LoadModule wsgi_module /usr/lib64/python3.6/site-packages/mod_wsgi/server/mod_wsgi-py36.cpython-36m-x86_64-linux-gnu.so
WSGIPythonPath /var/www/cgi-bin/***

WSGIScriptAlias / /var/www/cgi-bin/***/***/wsgi.py
Alias /static/ /var/www/cgi-bin/***/---/static/

&lt;Directory //var/www/cgi-bin/***/***/wsgi.py&gt;
  &lt;Files wsgi.py&gt;
    Require all granted
  &lt;/Files&gt;
&lt;/Directory&gt;

&lt;Directory /var/www/cgi-bin/***/---/static&gt;
    Require all granted
&lt;/Directory&gt;
</code></pre>

<p>＜Apache ssl.conf＞ 最終行に追記</p>

<pre><code>Alias /.well-known/acme-challenge/ /var/www/cgi-bin/***/---/.well-known/acme-challenge/
&lt;location .well-known=""&gt;
    Options -Indexes
&lt;/location&gt;
</code></pre>

<p>DNS側の問題のようですが、なかなか解決できず心が折れています・・・。<br>
もし、何か解決策や誤りがある場合はご教授くださいますようお願いいたします。</p>

<p>お忙しいところ大変申し訳ございませんが、よろしくお願いいたします。</p>
<!-- {% endraw %} -->
