---
layout: post
title: AttributeErrorの直し方
date: 2019-03-10 11:47:59
categories: python python3
---
<p>以下のエラーはどう直せばよいのでしょうか。</p>

<pre><code>C:\UsersDesktop&gt;python PrepareChain.py sample.txt
Traceback (most recent call last):
  File "PrepareChain.py", line 249, in &lt;module&gt;
    chain = PrepareChain(text)
  File "PrepareChain.py", line 33, in __init__
    text = text.decode("utf-8")
AttributeError: 'str' object has no attribute 'decode'
</code></pre>

<p>該当する行については</p>

<h3>33行目周辺</h3>

<pre><code>32 if isinstance(text, str):
33           text = text.decode("utf-8")
34        self.text = text
</code></pre>

<h3>249行目周辺</h3>

<pre><code> 243 f = open(param[1], encoding='utf-8')
 244   text = f.read()
 245   f.close()
 246
 247  # print (text)
 248
 249   chain = PrepareChain(text)
 250   triplet_freqs = chain.make_triplet_freqs()
 251   chain.save(triplet_freqs, True)
</code></pre>

<p>です。</p>
