---
layout: post
title: python-redmineでuserをfilterを利用したときの戻り値について
date: 2019-07-03 09:55:21
categories: python python3 redmine
---
<p>現在、以下のバージョン、ライブラリを利用してRedmineのActiveなユーザ情報を全て取得しようとしています。</p>

<ul>
<li>Python3.7</li>
<li>python-redmine</li>
</ul>

<p>対象のRedmineには一度のAPIで取得できる件数(100)を超えているのでページングするために、一度total_countを取得しようと以下のコードを書いてみたのですが、「user_list.total_count」を取得する際に <code>exceptions.ResultSetTotalCountError</code> が発生してしまいます。</p>

<pre class="lang-py prettyprint-override"><code>redmine = Redmine('https://example.com/redmine', key='XXXXXXXXXXXXXXXX')
user_list = redmine.user.filter(offset=1, limit=1, status=1)

repeat = user_list.total_count // 100
        if user_list.total_count % 100 &gt; 0:
            repeat += 1
        for i in range(0, repeat):
            offset = (i * 100 ) + 1
            user_list = redmine.user.filter(offset=offset, limit=100, status=1)
```

<p>そこで試しにuser_listが取得できてきないのかどうか、上記コードの1行目と2行目の間に以下のコードを追加すると、何の問題もなく正常に動作してしまいました。</p>

```
for user in user_list:
     print(user)
```

<p>なぜこれを追加するだけでうまくいってしまうのか理解できず、、for文を消してsleepを入れてみたり色々と試してみたのですが、原因がわからず気持ち悪いと感じております。</p>

<p>何か思い当たる方いらっしゃれば、Adviseいただけますと幸いです。よろしくお願いいたします。</p>
